clear; close all; clc;

load('BOUY.mat');

load("ASOS.mat");

load("snr_y2020_0423.mat");

mask1 = ismember(r_Date, b_Date);
mask2 = ismember(r_Date, asos_Date);
mask = mask1 & mask2;

r_Date = r_Date(mask);
r_surf_Pdir = r_surf_Pdir(mask);
r_surf_SNR = r_surf_SNR(mask);
r_surf_Tp = r_surf_Tp(mask);
r_surf_Ux = r_surf_Ux(mask);
r_surf_Uy = r_surf_Uy(mask);
r_wave_Pdir = r_wave_Pdir(mask);
r_wave_SNR = r_wave_SNR(mask);
r_wave_Tp = r_wave_Tp(mask);
r_wave_Ux = r_wave_Ux(mask);
r_wave_Uy = r_wave_Uy(mask);
r_LandE = r_LandE(mask);
r_WaveE = r_WaveE(mask);
r_SurfE = r_SurfE(mask);
r_surf_K_max = r_surf_K_max(mask);
r_surf_K_mean = r_surf_K_mean(mask);
r_surf_W_max = r_surf_W_max(mask);
r_surf_W_mean = r_surf_W_mean(mask);
r_wave_K_max = r_wave_K_max(mask);
r_wave_K_mean = r_wave_K_mean(mask);
r_wave_W_max = r_wave_W_max(mask);
r_wave_W_mean = r_wave_W_mean(mask);

clear mask1 mask2 mask

mask1 = ismember(b_Date, r_Date);
mask2 = ismember(b_Date, asos_Date);
mask = mask1 & mask2;

b_AirTemperature = b_AirTemperature(mask);
b_AtmosphericPressure = b_AtmosphericPressure(mask);
b_CurrentDirection16Points = b_CurrentDirection16Points(mask);
b_CurrentDirectiondeg = b_CurrentDirectiondeg(mask);
b_CurrentSpeed = b_CurrentSpeed(mask);
b_Date = b_Date(mask);
b_MaximumWaveHeight = b_MaximumWaveHeight(mask);
b_MaximumWavePeriod = b_MaximumWavePeriod(mask);
b_SignificantWaveHeight = b_SignificantWaveHeight(mask);
b_SignificantWavePeriod = b_SignificantWavePeriod(mask);
b_WaterTemperature = b_WaterTemperature(mask);
b_WindDirection16Points = b_WindDirection16Points(mask);
b_WindDirectiondeg = b_WindDirectiondeg(mask);
b_WindSpeed = b_WindSpeed(mask);
b_WaveDirection = b_WaveDirection(mask);

clear mask1 mask2 mask

mask1 = ismember(asos_Date, r_Date);
mask2 = ismember(asos_Date, b_Date);
mask = mask1 & mask2;

asos_Date = asos_Date(mask);
asos_Precipitation = asos_Precipitation(mask);

clear mask1 mask2 mask

r_surf_U = sqrt(r_surf_Ux.^2 + r_surf_Uy.^2);
r_wave_U = sqrt(r_wave_Ux.^2 + r_wave_Uy.^2);

data = [ ...
b_AirTemperature, ...
b_AtmosphericPressure, ...
double(b_CurrentDirection16Points), ...
b_CurrentDirectiondeg, ...
b_CurrentSpeed, ...
b_MaximumWaveHeight, ...
b_MaximumWavePeriod, ...
b_SignificantWaveHeight, ...
b_SignificantWavePeriod, ...
b_WaterTemperature, ...
double(b_WindDirection16Points), ...
b_WindDirectiondeg, ...
b_WindSpeed, ...
b_WaveDirection, ...
r_surf_Pdir, ...
r_surf_SNR, ...
r_surf_Tp, ...
r_surf_U, ...
r_wave_Pdir, ...
r_wave_SNR, ...
r_wave_Tp, ...
r_wave_U, ...
r_LandE, ...
r_WaveE, ...
r_SurfE, ...
r_surf_K_max, ...
r_surf_K_mean, ...
r_surf_W_max, ...
r_surf_W_mean, ...
r_wave_K_max, ...
r_wave_K_mean, ...
r_wave_W_max, ...
r_wave_W_mean, ...
asos_Precipitation, ...
(asos_Precipitation > 0)
];

varNames = { ...
' b AirTemperature', ...
' b AtmosphericPressure', ...
' b CurrentDirection16Points', ...
' b CurrentDirectiondeg', ...
' b CurrentSpeed', ...
' b MaximumWaveHeight', ...
' b MaximumWavePeriod', ...
' b SignificantWaveHeight', ...
' b SignificantWavePeriod', ...
' b WaterTemperature', ...
' b WindDirection16Points', ...
' b WindDirectiondeg', ...
' b WindSpeed', ...
' b WaveDirection', ...
' r surf Pdir', ...
' r surf SNR', ...
' r surf Tp', ...
' r surf U', ...
' r wave Pdir', ...
' r wave SNR', ...
' r wave Tp', ...
' r wave U', ...
' r LandE', ...
' r WaveE', ...
' r SurfE', ...
' r surf K max', ...
' r surf K mean', ...
' r surf W max', ...
' r surf W mean', ...
' r wave K max', ...
' r wave K mean', ...
' r wave W max', ...
' r wave W mean', ...
' asos Precipitation', ...
' asos RainTF'
};

R = corrcoef(data, 'Rows', 'pairwise');

figure(1);
h = heatmap(varNames, varNames, R);
title('Correlation Factors')